import { Connection, PublicKey, Keypair } from '@solana/web3.js';
import { Program, AnchorProvider, BN } from '@coral-xyz/anchor';

// Import program types (these would be generated by anchor build)
// For now, we'll use placeholder types
type AxiomId = any;
type AxiomStaking = any;
type AxiomPoHW = any;
type AxiomAttestations = any;
type ZentixProtocol = any;

// Import SDK modules
import { IdentityClient } from './clients/identity';
import { StakingClient } from './clients/staking';
import { PoHWClient } from './clients/pohw';
import { AttestationClient } from './clients/attestations';
import { ZentixClient } from './clients/zentix';

export class AxiomStackSDK {
  private connection: Connection;
  private provider: AnchorProvider;
  
  public identity: IdentityClient;
  public staking: StakingClient;
  public pohw: PoHWClient;
  public attestations: AttestationClient;
  public zentix: ZentixClient;

  constructor(
    connection: Connection,
    provider: AnchorProvider
  ) {
    this.connection = connection;
    this.provider = provider;
    
    // Initialize clients
    this.identity = new IdentityClient(connection, provider);
    this.staking = new StakingClient(connection, provider);
    this.pohw = new PoHWClient(connection, provider);
    this.attestations = new AttestationClient(connection, provider);
    this.zentix = new ZentixClient(connection, provider);
  }

  /**
   * Initialize all program clients with their respective programs
   * @param programs Object containing all program instances
   */
  async initializePrograms(programs: {
    axiomIdProgram: Program<AxiomId>,
    axiomStakingProgram: Program<AxiomStaking>,
    axiomPoHWProgram: Program<AxiomPoHW>,
    axiomAttestationsProgram: Program<AxiomAttestations>,
    zentixProgram: Program<ZentixProtocol>
  }) {
    this.identity.initialize(programs.axiomIdProgram);
    this.staking.initialize(programs.axiomStakingProgram);
    this.pohw.initialize(programs.axiomPoHWProgram);
    this.attestations.initialize(programs.axiomAttestationsProgram);
    this.zentix.initialize(programs.zentixProgram);
  }
}

export * from './clients/identity';
export * from './clients/staking';
export * from './clients/pohw';
export * from './clients/attestations';
export * from './clients/zentix';
export * from './types';

export default AxiomStackSDK;