import { Connection, PublicKey, Keypair } from '@solana/web3.js';
import { Program, AnchorProvider, BN } from '@coral-xyz/anchor';

// Import program types (these would be generated by anchor build)
// For now, we'll use placeholder types
type AgentSoulFactory = any;
type AxiomStaking = any;
type AxiomId = any;
type AxiomAttestations = any;
type AxiomPayments = any;
type AxiomSlashing = any;
type AxiomToken = any;
type AxiomGovernance = any;
type AxiomPoHW = any;
type AxiomStakingDynamic = any;

// Import SDK modules
import { IdentityClient } from './identity';
import { StakingClient } from './staking';
import { AttestationClient } from './attestations';
import { PaymentClient } from './payments';
import { SlashingClient } from './slashing';
import { PoHWClient } from './pohw';
import { DynamicStakingClient } from './dynamic-staking';

export class AxiomIDSDK {
  private connection: Connection;
  private provider: AnchorProvider;
  
  public identity: IdentityClient;
  public staking: StakingClient;
  public attestations: AttestationClient;
  public payments: PaymentClient;
  public slashing: SlashingClient;
  public pohw: PoHWClient;
  public dynamicStaking: DynamicStakingClient;

  constructor(
    connection: Connection,
    provider: AnchorProvider
  ) {
    this.connection = connection;
    this.provider = provider;
    
    // Initialize clients
    this.identity = new IdentityClient(connection, provider);
    this.staking = new StakingClient(connection, provider);
    this.attestations = new AttestationClient(connection, provider);
    this.payments = new PaymentClient(connection, provider);
    this.slashing = new SlashingClient(connection, provider);
    this.pohw = new PoHWClient(connection, provider);
    this.dynamicStaking = new DynamicStakingClient(connection, provider);
  }

  /**
   * Initialize all program clients with their respective programs
   * @param programs Object containing all program instances
   */
  async initializePrograms(programs: {
    agentSoulFactoryProgram: Program<AgentSoulFactory>,
    axiomStakingProgram: Program<AxiomStaking>,
    axiomIdProgram: Program<AxiomId>,
    axiomAttestationsProgram: Program<AxiomAttestations>,
    axiomPaymentsProgram: Program<AxiomPayments>,
    axiomSlashingProgram: Program<AxiomSlashing>,
    axiomTokenProgram: Program<AxiomToken>,
    axiomGovernanceProgram: Program<AxiomGovernance>,
    axiomPoHWProgram?: Program<AxiomPoHW>,
    axiomStakingDynamicProgram?: Program<AxiomStakingDynamic>
  }) {
    this.identity.initialize(programs.axiomIdProgram, programs.agentSoulFactoryProgram);
    this.staking.initialize(programs.axiomStakingProgram);
    this.attestations.initialize(programs.axiomAttestationsProgram);
    this.payments.initialize(programs.axiomPaymentsProgram);
    this.slashing.initialize(programs.axiomSlashingProgram);
    
    // Initialize PoHW if provided
    if (programs.axiomPoHWProgram) {
      this.pohw.initialize(programs.axiomPoHWProgram);
    }
    
    // Initialize dynamic staking if provided
    if (programs.axiomStakingDynamicProgram) {
      this.dynamicStaking.initialize(programs.axiomStakingDynamicProgram);
    }
  }
}

export * from './identity';
export * from './staking';
export * from './attestations';
export * from './payments';
export * from './slashing';
export * from './pohw';
export * from './dynamic-staking';
export * from './types';

export default AxiomIDSDK;